/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.List;
import controller.*;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.HoaDonBan;
import model.KhachHang;
import model.LoaiSanPham;
import model.SanPham;
import model.ThuongHieu;

/**
 *
 * @author MinhNguyenCong
 */
public class BanHang extends javax.swing.JInternalFrame {

    private List<LoaiSanPham> listLoaiSanPham;
    private List<ThuongHieu> listThuongHieu;
    private List<SanPham> listSanPham;
    private List<KhachHang> listKhachHang;
    private List<HoaDonBan> listHoaDonBan;
    private DefaultTableModel model;
    private String columns[] = {"Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Thành tiền"};
    private int index = -1;
    private int manv = -1;

    /**
     * Creates new form BanHang
     */
    public BanHang() {
        initComponents();
        tblHoaDon.setModel(model = new DefaultTableModel(columns, 0));
        manv = ManHinhChinh.getManv();
        khoiTao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        lblHinhAnh = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoaForm = new javax.swing.JButton();
        btnThanhToan = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cboThuongHieu = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cboLoaiSanPham = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cboMaSanPham = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtTenSanPham = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtGiaThanh = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cboMaKhachHang = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        lblThanhTien = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Bán Hàng");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Bán Hàng");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Số lượng", "Thành tiền"
            }
        ));
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        lblHinhAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinhAnh.setText("Hình Ảnh");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesbt/Delete.png"))); // NOI18N
        btnXoa.setText("Xóa SP");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesbt/Add.png"))); // NOI18N
        btnThem.setText("Thêm SP");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoaForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesbt/Delete.png"))); // NOI18N
        btnXoaForm.setText("Xóa Bảng");
        btnXoaForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaFormActionPerformed(evt);
            }
        });

        btnThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesbt/icons8_refund_48px.png"))); // NOI18N
        btnThanhToan.setText("Thanh Toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnXoa)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoaForm))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addGap(18, 18, 18)
                        .addComponent(btnThanhToan)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnThanhToan, btnThem, btnXoa, btnXoaForm});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnThanhToan))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa)
                    .addComponent(btnXoaForm))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnThanhToan, btnThem, btnXoa, btnXoaForm});

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Thương hiệu :");

        cboThuongHieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboThuongHieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboThuongHieuActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Loại sản phẩm :");

        cboLoaiSanPham.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLoaiSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiSanPhamActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Mã sản phẩm :");

        cboMaSanPham.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboMaSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMaSanPhamActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("Tên sản phẩm :");

        txtTenSanPham.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("Giá thành :");

        txtGiaThanh.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Số lượng :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Mã khách hàng :");

        cboMaKhachHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboMaKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMaKhachHangActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText("Tổng tiền :");

        lblThanhTien.setText("..........");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboMaKhachHang, 0, 199, Short.MAX_VALUE)
                                    .addComponent(lblThanhTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtGiaThanh, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(57, 57, 57)
                                .addComponent(txtSoLuong))
                            .addComponent(txtTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cboLoaiSanPham, cboMaKhachHang, cboMaSanPham, cboThuongHieu, txtGiaThanh, txtSoLuong, txtTenSanPham});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cboMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtGiaThanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cboMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblThanhTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cboLoaiSanPham, cboMaKhachHang, cboMaSanPham, cboThuongHieu, lblThanhTien, txtGiaThanh, txtSoLuong, txtTenSanPham});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblHinhAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblHinhAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboLoaiSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiSanPhamActionPerformed
        // TODO add your handling code here:
        try {
            loadDataToComboboxMSP();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cboLoaiSanPhamActionPerformed

    private void cboThuongHieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboThuongHieuActionPerformed
        // TODO add your handling code here:
        try {
            loadDataToComboboxMSP();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cboThuongHieuActionPerformed

    private void cboMaSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMaSanPhamActionPerformed
        // TODO add your handling code here:
        try {
            loadTenSanPham();
            loadImagesToLabel();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cboMaSanPhamActionPerformed

    private void cboMaKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMaKhachHangActionPerformed
        // TODO add your handling code here:
        try {

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cboMaKhachHangActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        try {
            if (checkNull()) {
                return;
            }
            if (checkNumber()) {
                return;
            }
            fillToTable();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaFormActionPerformed
        // TODO add your handling code here:
        try {
            int hoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa toàn bộ sản phẩm đã thêm ?");
            if (hoi != JOptionPane.YES_OPTION) {
                return;
            }
            model.setRowCount(0);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnXoaFormActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        try {
            if (checkRow()) {
                return;
            }
            model.removeRow(index);
            index = -1;
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        // TODO add your handling code here:
        try {
            index = tblHoaDon.getSelectedRow();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
        try {
            if (tblHoaDon.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Không có gì để thanh toán");
                return;
            }
            int hoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn thanh toán ?");
            if (hoi != JOptionPane.YES_OPTION) {
                return;
            }
            int tongTien = 0;
            for (int i = 0; i < tblHoaDon.getRowCount(); i++) {
                tongTien += Integer.parseInt(tblHoaDon.getValueAt(i, 3).toString());
            }
            lblThanhTien.setText(tongTien+"");
            // lưu hóa đơn và hóa đơn chi tiết vào database
            BanHangDAO.saveHDToDatabase(tongTien, Integer.parseInt(cboMaKhachHang.getSelectedItem().toString()), manv);
            int mahd = BanHangDAO.getHoaDonBanCN();
            for (int i = 0; i < tblHoaDon.getRowCount(); i++) {
                BanHangDAO.saveHDCTToDatabase(mahd, Integer.parseInt(tblHoaDon.getValueAt(i, 0).toString()), Integer.parseInt(tblHoaDon.getValueAt(i, 2).toString()));
            }
            JOptionPane.showMessageDialog(this, "Thanh toán thành công !" + "\n Số tiền cần phải thanh toán là : " + tongTien);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void loadDataToComboboxLSP() {
        try {
            cboLoaiSanPham.removeAllItems();
            listLoaiSanPham = BanHangDAO.getLoaiSanPhams();
            for (LoaiSanPham o : listLoaiSanPham) {
                cboLoaiSanPham.addItem(o.getTenLoaiSanPham());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadDataToComboboxTTH() {
        try {
            cboThuongHieu.removeAllItems();
            listThuongHieu = BanHangDAO.getThuongHieu();
            for (ThuongHieu o : listThuongHieu) {
                cboThuongHieu.addItem(o.getTenThuongHieu());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadDataToComboboxMSP() {
        try {
            cboMaSanPham.removeAllItems();
            listSanPham = BanHangDAO.getSanPham();
            int maLoaiSanPham = -1;
            int maLoaiThuongHieu = -1;
            for (LoaiSanPham o : listLoaiSanPham) {
                if (cboLoaiSanPham.getSelectedItem().toString().equalsIgnoreCase(o.getTenLoaiSanPham())) {
                    maLoaiSanPham = o.getMaLoaiSanPham();
                    break;
                }
            }
            for (ThuongHieu o : listThuongHieu) {
                if (cboThuongHieu.getSelectedItem().toString().equalsIgnoreCase(o.getTenThuongHieu())) {
                    maLoaiThuongHieu = o.getMaThuongHieu();
                    break;
                }
            }
            for (SanPham o : listSanPham) {
                if (o.getMaLoaiSanPham() == maLoaiSanPham && o.getMaLoaiThuongHieu() == maLoaiThuongHieu) {
                    cboMaSanPham.addItem(o.getMaSanPham() + "");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadTenSanPham() {
        try {
            if (cboMaSanPham.getSelectedItem() == null) {
                return;
            }
            for (SanPham o : listSanPham) {
                if ((Integer.parseInt(cboMaSanPham.getSelectedItem().toString())) == o.getMaSanPham()) {
                    txtTenSanPham.setText(o.getTenSanPham());
                    txtGiaThanh.setText(o.getGiaSanPham() + "");
                    break;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private boolean checkNull() {
        try {
            if (txtSoLuong.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Số lượng không được để trống");
                return true;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return false;
    }

    private boolean checkNumber() {
        try {
            Integer.parseInt(txtSoLuong.getText());
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Số lượng phải là số nguyên!");
            return true;
        }
        return false;
    }

    private boolean checkRow() {
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm muốn xóa ở dưới bảng.");
            return true;
        }
        return false;
    }

    private void loadDataToComboboxKH() {
        try {
            cboMaKhachHang.removeAllItems();
            listKhachHang = BanHangDAO.getKhachHang();
            for (KhachHang o : listKhachHang) {
                cboMaKhachHang.addItem(o.getMaKhachHang() + "");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadImagesToLabel() {
        try {
            String hinhAnh = null;
            int mSP = -1;
            if (cboMaSanPham.getSelectedItem() == null) {
                return;
            }
            mSP = Integer.parseInt(cboMaSanPham.getSelectedItem().toString());
            for (SanPham o : listSanPham) {
                if (mSP == o.getMaSanPham()) {
                    hinhAnh = o.getAnh();
                    break;
                }
            }
            if (hinhAnh == null) {
                return;
            }
            File file = new File("C:\\Users\\MinhNguyenCong\\Documents\\NetBeansProjects\\QLCHBXD\\src\\imagesxd\\" + hinhAnh);
            Image img = ImageIO.read(file);
            int width = 384;
            int height = 214;
            lblHinhAnh.setText(null);
            lblHinhAnh.setIcon(new ImageIcon(img.getScaledInstance(width, height, img.SCALE_DEFAULT)));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void fillToTable() {
        try {
            int msp = Integer.parseInt(cboMaSanPham.getSelectedItem().toString());
            String tsp = txtTenSanPham.getText();
            int sl = Integer.parseInt(txtSoLuong.getText());
            int gt = Integer.parseInt(txtGiaThanh.getText());
            int tt = (gt * sl);
            if (tblHoaDon.getRowCount() == 0) {
                model.addRow(new Object[]{msp, tsp, sl, tt});
                return;
            }
            if (0 < tblHoaDon.getRowCount()) {
                for (int i = 0; i < tblHoaDon.getRowCount(); i++) {
                    if (msp == Integer.parseInt(tblHoaDon.getValueAt(i, 0).toString())) {
                        model.addRow(new Object[]{msp, tsp, sl + Integer.parseInt(tblHoaDon.getValueAt(i, 2).toString()), tt + Integer.parseInt(tblHoaDon.getValueAt(i, 3).toString())});
                        model.removeRow(i);
                        return;
                    }
                }
            }
            for (int i = 0; i < tblHoaDon.getRowCount(); i++) {
                if (msp != Integer.parseInt(tblHoaDon.getValueAt(i, 0).toString())) {
                    model.addRow(new Object[]{msp, tsp, sl, tt});
                    return;
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void khoiTao() {
        listLoaiSanPham = new ArrayList<>();
        listThuongHieu = new ArrayList<>();
        listSanPham = new ArrayList<>();
        listKhachHang = new ArrayList<>();
        loadDataToComboboxLSP();
        loadDataToComboboxTTH();
        loadDataToComboboxMSP();
        loadTenSanPham();
        loadDataToComboboxKH();
        // lấy mã nhân viên
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaForm;
    private javax.swing.JComboBox<String> cboLoaiSanPham;
    private javax.swing.JComboBox<String> cboMaKhachHang;
    private javax.swing.JComboBox<String> cboMaSanPham;
    private javax.swing.JComboBox<String> cboThuongHieu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHinhAnh;
    private javax.swing.JLabel lblThanhTien;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTextField txtGiaThanh;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSanPham;
    // End of variables declaration//GEN-END:variables
}
