/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.HoaDonCTDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MinhNguyenCong
 */
public class HoaDonBanCT extends javax.swing.JInternalFrame {
    private DefaultTableModel model = null;
    private String columns [] = {"Mã hóa đơn","Mã sản phẩm","Tên sản phẩm","Giá sản phẩm","Số lượng"};
    private List<model.HoaDonBanCT> listHoaDonCT = null;
    private int maHD = -1;
    /**
     * Creates new form HoaDonBanCT
     */
    public HoaDonBanCT(int maHD) {
        initComponents();
        tblHoaDonCT.setModel(model = new DefaultTableModel(columns, 0));
        this.maHD = maHD;
        fillDataToTable(this.maHD);
    }
    
    private void fillDataToTable(int maHD){
        listHoaDonCT = HoaDonCTDAO.getHoaDonCT(maHD);
        try {
            model.setRowCount(0);
            for (model.HoaDonBanCT o : listHoaDonCT) {
                model.addRow(new Object[]{o.getMaHoaDonBan(), o.getMaSanPham(), o.getTenSanPham(), o.getGiaSanPham(), o.getSoLuong()});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDonCT = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);

        tblHoaDonCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblHoaDonCT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHoaDonCT;
    // End of variables declaration//GEN-END:variables
}
