/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.HoaDonChiDAO;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.HoaDonChi;
import model.NhanVien;

/**
 *
 * @author MinhNguyenCong
 */
public class QLHoaDonChi extends javax.swing.JInternalFrame {

    private DefaultTableModel model;
    private String columns[] = {"Mã hóa đơn chi", "Mục đích", "Thành tiền", "Ngày tạo", "Mã nhân viên"};
    private List<HoaDonChi> listHoaDonChi;
    private List<NhanVien> listNhanVien;
    private int index = -1;

    /**
     * Creates new form HoaDonChi
     */
    public QLHoaDonChi() {
        initComponents();
        tblChiTieu.setModel(model = new DefaultTableModel(columns, 0));
        fillDataToTable();
        fillDataToCombobox();
        setTenNV();
    }

    private void fillDataToTable() {
        try {
            listHoaDonChi = new ArrayList<>();
            listHoaDonChi = HoaDonChiDAO.getHDC();
            if (listHoaDonChi == null) {
                return;
            }
            model.setRowCount(0);
            for (HoaDonChi o : listHoaDonChi) {
                model.addRow(new Object[]{o.getMaHoaDonChi(), o.getMucDich(), o.getThanhTien(), o.getNgayTao(), o.getMaNhanVien()});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void fillDataToCombobox() {
        try {
            listNhanVien = new ArrayList<>();
            listNhanVien = HoaDonChiDAO.getNhanVien();
            cboMaNhanVien.removeAllItems();
            for (NhanVien o : listNhanVien) {
                cboMaNhanVien.addItem(o.getMaNhanVien() + "");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void setTenNV() {
        try {
            String tenNV = "Không có tên";
            int manv = -1;
            for (NhanVien o : listNhanVien) {
                manv = o.getMaNhanVien();
            }
            if (manv == -1 || cboMaNhanVien.getItemCount() == 0) {
                return;
            }
            for (NhanVien o : listNhanVien) {
                if (o.getMaNhanVien() == Integer.parseInt(cboMaNhanVien.getSelectedItem().toString())) {
                    tenNV = o.getHoTen();
                    txtTenNV.setText(tenNV);
                    return;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private boolean checkNull() {
        if (txtMucDich.getText().isEmpty() || txtNgayChi.getText().isEmpty() || txtSoTien.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Các mục không được để trống");
            return true;
        } else {
            return false;
        }
    }

    private boolean checkSo() {
        try {
            int so = Integer.parseInt(txtSoTien.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Số tiền phải là số nguyên");
            return true;
        }
        return false;
    }

    private boolean checkNC() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date date = sdf.parse(txtNgayChi.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Định dạng ngày phải là : yyyy-MM-dd");
            return true;
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChiTieu = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        cboMaNhanVien = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtNgayChi = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtSoTien = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtMucDich = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnTaoHoaDon = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnXoaForm = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        txtTenNV = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Quản Lý Hóa Đơn Chi");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Chi Tiêu");

        tblChiTieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblChiTieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChiTieuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblChiTieu);

        jLabel16.setText("Mã nhân viên :");

        cboMaNhanVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboMaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMaNhanVienActionPerformed(evt);
            }
        });

        jLabel17.setText("Họ tên nhân viên :");

        jLabel18.setText("Ngày chi :");

        txtNgayChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayChiActionPerformed(evt);
            }
        });

        jLabel19.setText("Số tiền :");

        jLabel20.setText("Mục đích :");

        txtMucDich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMucDichActionPerformed(evt);
            }
        });

        btnTaoHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesbt/Add.png"))); // NOI18N
        btnTaoHoaDon.setText("Tạo hóa đơn");
        btnTaoHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoHoaDonActionPerformed(evt);
            }
        });

        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesbt/refresh.png"))); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnXoaForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesbt/Delete.png"))); // NOI18N
        btnXoaForm.setText("Xóa Form");
        btnXoaForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaFormActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesbt/Edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTaoHoaDon)
                    .addComponent(btnLamMoi))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoaForm)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnLamMoi, btnSua, btnTaoHoaDon, btnXoaForm});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTaoHoaDon)
                    .addComponent(btnXoaForm))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLamMoi)
                    .addComponent(btnSua))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtTenNV.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMucDich)
                            .addComponent(cboMaNhanVien, 0, 190, Short.MAX_VALUE)
                            .addComponent(txtNgayChi)
                            .addComponent(txtSoTien)
                            .addComponent(txtTenNV))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cboMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtNgayChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtSoTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtMucDich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNgayChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayChiActionPerformed

    private void txtMucDichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMucDichActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMucDichActionPerformed

    private void cboMaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMaNhanVienActionPerformed
        // TODO add your handling code here:
        try {
            setTenNV();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cboMaNhanVienActionPerformed

    private void tblChiTieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChiTieuMouseClicked
        // TODO add your handling code here:
        try {
            if (tblChiTieu.getRowCount() == 0) {
                return;
            }
            
            index = tblChiTieu.getSelectedRow();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblChiTieuMouseClicked

    private void btnTaoHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoHoaDonActionPerformed
        // TODO add your handling code here:
        try {
            if (checkNull()) {
                return;
            }
            if (checkSo()) {
                return;
            }
            if (checkNC()) {
                return;
            }
            int hoi = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn tạo hóa đơn này?");
            if (hoi != JOptionPane.YES_OPTION) {
                return;
            }
            int soTien = Integer.parseInt(txtSoTien.getText());
            HoaDonChiDAO.saveHDC(txtMucDich.getText(), soTien, txtNgayChi.getText(), Integer.parseInt(cboMaNhanVien.getSelectedItem().toString()));
            JOptionPane.showMessageDialog(this, "Thêm thành công!");
            fillDataToTable();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTaoHoaDonActionPerformed

    private void btnXoaFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaFormActionPerformed
        // TODO add your handling code here:
        try {
            txtMucDich.setText(null);
            txtNgayChi.setText(null);
            txtSoTien.setText(null);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnXoaFormActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        try {
            fillDataToTable();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        try {
            if (index == -1) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn hóa đơn muốn sửa trong bảng");
                return;
            }
            if (checkNull()) {
                return;
            }
            if (checkSo()) {
                return;
            }
            if (checkNC()) {
                return;
            }
            int hoi = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn sửa hóa đơn này?");
            if (hoi != JOptionPane.YES_OPTION) {
                return;
            }
            int soTien = Integer.parseInt(txtSoTien.getText());
            HoaDonChiDAO.updateHDC(txtMucDich.getText(), soTien, txtNgayChi.getText(), Integer.parseInt(cboMaNhanVien.getSelectedItem().toString()), Integer.parseInt(tblChiTieu.getValueAt(index, 0).toString()));
            JOptionPane.showMessageDialog(this, "Sửa thành công!");
            fillDataToTable();
            index = -1;
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSuaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTaoHoaDon;
    private javax.swing.JButton btnXoaForm;
    private javax.swing.JComboBox<String> cboMaNhanVien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblChiTieu;
    private javax.swing.JTextField txtMucDich;
    private javax.swing.JTextField txtNgayChi;
    private javax.swing.JTextField txtSoTien;
    private javax.swing.JTextField txtTenNV;
    // End of variables declaration//GEN-END:variables
}
