/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.NhanVienDAO;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.NhanVien;
import model.SanPham;

/**
 *
 * @author MinhNguyenCong
 */
public class QuanLyNhanVien extends javax.swing.JInternalFrame {

    private List<NhanVien> listNhanVien;
    DefaultTableModel model;
    String columns[] = {"Mã nhân viên", "Họ tên", "Giới tính", "Ngày sinh", "Quê quán", "Số điện thoại", "Email", "Ảnh", "Chức vụ"};
    private int index = -1;
    private int maNV = -1;
    private String hinhAnh = null;
    private int sua = -1;
    private File f = null;
    private String path = null;
    private String tenHinhAnh = null;
    private int width = -1;
    private int height = -1;

    /**
     * Creates new form QuanLyNhanVien1
     */
    public QuanLyNhanVien() {
        initComponents();
        tblQuanLyNhanVien.setModel(model = new DefaultTableModel(columns, 0));
        listNhanVien = new ArrayList<>();
        rdoNam.setSelected(true);
        fillDataToTable();
        setImgToLabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtQueQuan = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        btnXoaTrang = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JPasswordField();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        cboChucVu = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtMaNhanVienTK = new javax.swing.JTextField();
        btnTimKiemNhanVien = new javax.swing.JButton();
        lblHinhAnh = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQuanLyNhanVien = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Quản Lý Nhân Viên");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Họ tên :");

        jLabel4.setText("Giới tính :");

        jLabel6.setText("Quê Quán :");

        jLabel7.setText("Số điện thoại :");

        jLabel8.setText("Email :");

        jLabel5.setText("Ngày sinh :");

        btnXoaTrang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesbt/Delete.png"))); // NOI18N
        btnXoaTrang.setText("Xóa Form");
        btnXoaTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTrangActionPerformed(evt);
            }
        });

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesbt/Add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesbt/refresh.png"))); // NOI18N
        btnXoa.setText("Làm Mới");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesbt/Edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jLabel10.setText("Tài Khoản :");

        jLabel11.setText("Mật Khẩu :");

        txtMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatKhauActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoNam);
        rdoNam.setText("Nam");

        buttonGroup1.add(rdoNu);
        rdoNu.setText("Nữ");

        jLabel2.setText("Chức vụ :");

        cboChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản lý", "Nhân viên" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel2))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addComponent(txtQueQuan, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rdoNam)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdoNu))
                                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addComponent(txtTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addComponent(txtMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addComponent(cboChucVu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnXoa)
                                    .addComponent(btnXoaTrang))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSua, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnThem, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSua, btnThem, btnXoa, btnXoaTrang});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {rdoNam, rdoNu});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rdoNam)
                    .addComponent(rdoNu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoaTrang)
                    .addComponent(btnThem))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa)
                    .addComponent(btnSua))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setText("Mã Nhân viên:");

        btnTimKiemNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesbt/Search.png"))); // NOI18N
        btnTimKiemNhanVien.setText("Tìm kiếm nhân viên");
        btnTimKiemNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemNhanVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(90, 90, 90))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(txtMaNhanVienTK, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnTimKiemNhanVien)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaNhanVienTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTimKiemNhanVien)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        lblHinhAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinhAnh.setText("Hình ảnh");
        lblHinhAnh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblHinhAnh.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblHinhAnhAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        lblHinhAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhAnhMouseClicked(evt);
            }
        });

        tblQuanLyNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblQuanLyNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQuanLyNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblQuanLyNhanVien);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Quản Lý Nhân Viên");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                                .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(148, 148, 148)))
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(408, 408, 408)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTrangActionPerformed
        // TODO add your handling code here:
        try {
            txtHoTen.setText("");
            txtQueQuan.setText("");
            txtSoDienThoai.setText("");
            txtEmail.setText("");
            txtNgaySinh.setText("");
            txtTaiKhoan.setText("");
            txtMatKhau.setText("");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnXoaTrangActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        try {
            fillDataToTable();
            setImgToLabel();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblQuanLyNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQuanLyNhanVienMouseClicked
        // TODO add your handling code here:
        try {
            sua = tblQuanLyNhanVien.getSelectedRow();
            index = tblQuanLyNhanVien.getSelectedRow();
            maNV = Integer.parseInt(tblQuanLyNhanVien.getValueAt(index, 0).toString());
            if (tblQuanLyNhanVien.getRowCount() == 0) {
                return;
            }
            if (tblQuanLyNhanVien.getValueAt(index, 7) == null) {
                File file = new File("C:\\Users\\MinhNguyenCong\\Documents\\NetBeansProjects\\QLCHBXD\\src\\imagesnv\\qlsv1.png");
                Image img = ImageIO.read(file);
                int width = 152;
                int height = 152;
                lblHinhAnh.setText(null);
                lblHinhAnh.setIcon(new ImageIcon(img.getScaledInstance(width, height, 0)));
                return;
            }
            File file = new File("C:\\Users\\MinhNguyenCong\\Documents\\NetBeansProjects\\QLCHBXD\\src\\imagesnv\\" + tblQuanLyNhanVien.getValueAt(index, 7));
            Image img = ImageIO.read(file);
            int width = 152;
            int height = 152;
            lblHinhAnh.setText(null);
            lblHinhAnh.setIcon(new ImageIcon(img.getScaledInstance(width, height, 0)));
            index = -1;
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblQuanLyNhanVienMouseClicked

    private void lblHinhAnhAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblHinhAnhAncestorAdded
//         TODO add your handling code here:
    }//GEN-LAST:event_lblHinhAnhAncestorAdded

    private void btnTimKiemNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemNhanVienActionPerformed
        // TODO add your handling code here:
        try {
            if (txtMaNhanVienTK.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ô tìm kiếm không được để trống!");
                return;
            }
            if (checkSo()) {
                return;
            }
            for (NhanVien o : listNhanVien) {
                if (o.getMaNhanVien() == Integer.parseInt(txtMaNhanVienTK.getText())) {
                    model.setRowCount(0);
                    model.addRow(new Object[]{o.getMaNhanVien(), o.getHoTen(), checkGT(o.getGioiTinh()), o.getNgaySinh(), o.getQueQuan(), o.getSoDienThoai(), o.getEmail(), o.getAnh(), checkCV(o.getChucVu())});
                    if (o.getAnh() != null) {
                        File file = new File("C:\\Users\\MinhNguyenCong\\Documents\\NetBeansProjects\\QLCHBXD\\src\\imagesnv\\" + o.getAnh());
                        Image img = ImageIO.read(file);
                        int width = 152;
                        int height = 152;
                        lblHinhAnh.setText(null);
                        lblHinhAnh.setIcon(new ImageIcon(img.getScaledInstance(width, height, 0)));
                    } else {
                        File file = new File("C:\\Users\\MinhNguyenCong\\Documents\\NetBeansProjects\\QLCHBXD\\src\\imagesnv\\qlsv1.png");
                        Image img = ImageIO.read(file);
                        int width = 152;
                        int height = 152;
                        lblHinhAnh.setText(null);
                        lblHinhAnh.setIcon(new ImageIcon(img.getScaledInstance(width, height, 0)));
                    }
                    return;
                }
            }
            JOptionPane.showMessageDialog(this, "Không tìm thấy!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTimKiemNhanVienActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        try {
            if (checkNull()) {
                return;
            }
            if (checkSo1()) {
                return;
            }
            if (checkNS()) {
                return;
            }
            int hoi = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thêm nhân viên?");
            if (hoi != JOptionPane.YES_OPTION) {
                return;
            }
            NhanVienDAO.insertNV(txtHoTen.getText(), checkGT(), txtNgaySinh.getText(), txtQueQuan.getText(), txtSoDienThoai.getText(), txtEmail.getText(), tenHinhAnh, checkCV());
            maNV = NhanVienDAO.getMaNV();
            NhanVienDAO.setTK(txtTaiKhoan.getText(), txtMatKhau.getText(), maNV);

            if (tenHinhAnh != null) {
                f = new File(path);
                BufferedImage image = ImageIO.read(f);
                f = new File("C:\\Users\\MinhNguyenCong\\Documents\\NetBeansProjects\\QLCHBXD\\src\\imagesnv\\" + tenHinhAnh);
                ImageIO.write(image, "jpg", f);
            }
            tenHinhAnh = null;
            maNV = -1;
            fillDataToTable();
            JOptionPane.showMessageDialog(this, "Thêm thành công!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void txtMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatKhauActionPerformed
        // TODO add your handling code here
        txtMatKhau.setText("");
    }//GEN-LAST:event_txtMatKhauActionPerformed

    private void lblHinhAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhAnhMouseClicked
        // TODO add your handling code here:
        try {
            width = lblHinhAnh.getWidth();
            height = lblHinhAnh.getHeight();
            JFileChooser jfc = new JFileChooser();
            int i = jfc.showOpenDialog(this);
            if (i == JFileChooser.APPROVE_OPTION) {
                f = jfc.getSelectedFile();
                path = f.getAbsolutePath();
                tenHinhAnh = f.getName();
                BufferedImage image = ImageIO.read(f);
                lblHinhAnh.setText(null);
                lblHinhAnh.setIcon(new ImageIcon(image.getScaledInstance(width, height, 0)));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_lblHinhAnhMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        try {
            if (tblQuanLyNhanVien.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Không có gì để sửa");
                return;
            }
            if (sua == -1) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên ở trong bảng để sửa.");
                return;
            }
            if (checkNull()) {
                return;
            }
            if (checkSo1()) {
                return;
            }
            if (checkNS()) {
                return;
            }
            int hoi = JOptionPane.showConfirmDialog(this, "Bạn có chắc sửa thông tin nhân viên?");
            if (hoi != JOptionPane.YES_OPTION) {
                return;
            }
            System.out.println(maNV);
            if (tenHinhAnh != null) {
                f = new File(path);
                BufferedImage image = ImageIO.read(f);
                f = new File("C:\\Users\\MinhNguyenCong\\Documents\\NetBeansProjects\\QLCHBXD\\src\\imagesnv\\" + tenHinhAnh);
                ImageIO.write(image, "jpg", f);
            }
            NhanVienDAO.suaTK(txtTaiKhoan.getText(), txtMatKhau.getText(), maNV);
            NhanVienDAO.suaNV(txtHoTen.getText(), checkGT(), txtNgaySinh.getText(), txtQueQuan.getText(), txtSoDienThoai.getText(), txtEmail.getText(), tenHinhAnh, checkCV(), maNV);
            fillDataToTable();
            tenHinhAnh = null;
            maNV = -1;
            sua = -1;
            JOptionPane.showMessageDialog(this, "Sửa thành công!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void fillDataToTable() {
        try {
            listNhanVien = NhanVienDAO.getNhanVien();
            model.setRowCount(0);
            for (NhanVien o : listNhanVien) {
                model.addRow(new Object[]{o.getMaNhanVien(), o.getHoTen(), checkGT(o.getGioiTinh()), o.getNgaySinh(), o.getQueQuan(), o.getSoDienThoai(), o.getEmail(), o.getAnh(), checkCV(o.getChucVu())});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void setImgToLabel() {
        try {
            String hinhAnh = null;
            if (tblQuanLyNhanVien.getRowCount() == 0) {
                return;
            }
            hinhAnh = tblQuanLyNhanVien.getValueAt(0, 7).toString();
            if (hinhAnh == null) {
                return;
            }
            File file = new File("C:\\Users\\MinhNguyenCong\\Documents\\NetBeansProjects\\QLCHBXD\\src\\imagesnv\\" + hinhAnh);
            Image img = ImageIO.read(file);
            int width = 152;
            int height = 152;
            lblHinhAnh.setText(null);
            lblHinhAnh.setIcon(new ImageIcon(img.getScaledInstance(width, height, 0)));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private String checkGT(int gT) {
        if (gT == 1) {
            return "Nam";
        } else {
            return "Nữ";
        }
    }

    private String checkCV(int cV) {
        if (cV == 1) {
            return "Quản lý";
        } else {
            return "Nhân Viên";
        }
    }

    private int checkCV() {
        if (cboChucVu.getSelectedIndex() == 0) {
            return 1;
        } else {
            return 0;
        }
    }

    private int checkGT() {
        if (rdoNam.isSelected()) {
            return 1;
        } else {
            return 0;
        }
    }

    private boolean checkSo() {
        try {
            int so = Integer.parseInt(txtMaNhanVienTK.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Mã nhân viên phải là số nguyên!");
            return true;
        }
        return false;
    }

    private boolean checkSo1() {
        try {
            int so = Integer.parseInt(txtSoDienThoai.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Số điện thoại phải là số!");
            return true;
        }
        return false;
    }

    private boolean checkNull() {
        if (txtHoTen.getText().isEmpty() || txtQueQuan.getText().isEmpty() || txtSoDienThoai.getText().isEmpty() || txtEmail.getText().isEmpty() || txtNgaySinh.getText().isEmpty() || txtTaiKhoan.getText().isEmpty() || txtMatKhau.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Các ô không được để trống!");
            return true;
        }
        return false;
    }

    private boolean checkNS() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date date = sdf.parse(txtNgaySinh.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Định dạng ngày phải là : yyyy-MM-dd");
            return true;
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiemNhanVien;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaTrang;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboChucVu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHinhAnh;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTable tblQuanLyNhanVien;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaNhanVienTK;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtQueQuan;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
